= Export GPX Plugin

== Links

Source: https://github.com/twocanplugin/demo_plugin[Github Repository]

Releases: https://github.com/audiopilot/demo_plugin/releases[Github Releases]


Forum:
http://www.cruisersforum.com/forums/f134/demo_plugin.html[Cruiser's
Forum Demo Plugin Thread]

== Introduction

This plugin is derived from the Demo plugin, essentially branched from Chapter 5, demonstrating
both Context Menus and Toolbar buttons.

It performs a simple export of either a single waypoint or multiple waypoints using the 
standard GPX XML format. It is a "plain vanilla" export, which excludes the extensions that 
are used by OpenCPN, meaning that it should be able to be imported into any other commercial 
Multi Function Display (MFD) or third party application.

In some respects it addresses the problem described in the following post:
https://www.cruisersforum.com/forums/f134/opencpn-general-30946-140.html#post4063366

[source,cpp]
----
auto gpxMenu = new wxMenuItem(NULL, k_SecondContextMenu, "Export GPX", "Export Waypoint as GPX", wxITEM_NORMAL, NULL);
	exportWaypointMenuId = AddCanvasContextMenuItemExt(gpxMenu, this, "Waypoint");
----

And for the toolbar button:

[source,cpp]
----
wxString normalIcon = pluginFolder + "demo_icon_normal.svg";
wxString toggledIcon = pluginFolder + "demo_icon_toggled.svg";
wxString rolloverIcon = pluginFolder + "demo_icon_rollover.svg";

exportWaypointsToolbarId = InsertPlugInToolSVG("Demo", normalIcon,
	rolloverIcon, toggledIcon, wxITEM_CHECK, "Export Waypoints", "Export all waypoints", NULL, -1, 0, this);
----

It also cherry picks from from Chapter 11, Retrieving the properties of a waypoint.

[source,cpp]
----
PlugIn_Waypoint wpt;
GetSingleWaypoint(waypointGUID, &wpt);
----

It uses the bundled pugixml library to generate the XML document conforming the GPX schema.

[source,cpp]
----
pugi::xml_node node;
pugi::xml_node value;
node = gpx.append_child("wpt");
node.append_attribute("lat") = wpt.m_lat;
node.append_attribute("lon") = wpt.m_lon;
value = node.append_child("name");
value.append_child(pugi::node_pcdata).set_value(wpt.m_MarkName);
value = node.append_child("desc");
value.append_child(pugi::node_pcdata).set_value(wpt.m_MarkDescription);
----

----
