site:
  title: Demo Plugin Manual
  url:  https://nowhere.net
  start_page: demo_plugin:ROOT:index.adoc

content:
  sources:
    - url: ..
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/twocanplugin/demo_plugin/edit/master/{path}

ui:   
  bundle:
    url: https://gitlab.com/leamas/antora-ui-default/-/raw/master/latest/ui-bundle.zip
    snapshot: true

output:
  dir: ./docs
  clean: true              

asciidoc:
  attributes:
    copyright: 2025 Demo Plugin Author
    license: CC BY-SA 4.0
    license-link: https://creativecommons.org/licenses/by-sa/4.0/
